[build]
target = "index.html"
dist = "dist"
public_url = "/"
filehash = true

[watch]
watch = ["src", "index.html", "Cargo.toml", "tailwind.config.js"]

[serve]
address = "127.0.0.1"
port = 3000
open = true

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["tailwindcss", "-i", "./src/styles/main.scss", "-o", "./styles/output.css"] 